# Nova Model Whiteboard

This code is just me experimenting with building my own neural network, none of this has been unit tested, time or memory efficiency optimized, etc...

In [54]:
import numpy as np
import tensorflow as tf
from neuralnetworks import ffnn, embedding, attention, masking, transformer
from tokenization import tokenizer
import importlib

## Embedding Model Tests

In [5]:
importlib.reload(embedding)

<module 'neuralnetworks.embedding' from '/Users/joericks/Desktop/nova/model/neuralnetworks/embedding.py'>

In [34]:
e_dim = 40

e_layer = embedding.EmbeddingLayer(e_dim, name = "embedding")

e_layer("hello")
e_layer("world")

<tf.Tensor: shape=(40,), dtype=float32, numpy=
array([ 0.9466732 , -0.9517766 ,  0.6089755 , -1.7202418 ,  0.00536991,
       -2.1891122 ,  0.22489779, -1.9345222 , -0.64037246,  1.342186  ,
       -0.0755018 ,  1.6919665 , -0.5203122 , -1.8375303 , -2.4220014 ,
       -0.67197025,  2.5232656 , -2.2110374 ,  3.1824946 , -1.183102  ,
       -1.8224388 , -1.2308848 ,  2.4863615 ,  0.57052153, -0.31785262,
       -1.0713868 , -0.26481   ,  2.1472726 ,  0.3293893 , -1.3335986 ,
        2.2279396 ,  1.374608  , -0.5200319 ,  1.0549773 ,  0.414537  ,
        1.4100695 , -0.09097227, -1.5231383 ,  1.1515183 , -0.7249024 ],
      dtype=float32)>

In [35]:
other_layer = embedding.EmbeddingLayer(e_dim, name = "other_embedding")

other_layer("!")

other_layer("=")

other_layer (";")

new_layer = e_layer + other_layer

In [36]:
new_layer.h

{'hello': 0, 'world': 1, '!': 2, '=': 3, ';': 4}

Documentation on softmax and ReLU are provided below: <br>
**[ReLU](https://en.wikipedia.org/wiki/Rectifier_(neural_networks))** <br>
**[softmax](https://en.wikipedia.org/wiki/Softmax_function)**

In [37]:
#testing the performer attention head

sentence = ['hello', 'world']

idxs = [new_layer.h[s] for s in sentence if s in new_layer.h.keys()]

In [38]:
c = []

for i in idxs:
    c.append(new_layer.embeddings[i].numpy())

In [39]:
# then this process would get iterated based on the batches of training data passed through the model,
# but here we are going to cheat and just make this example be one batch

b = []

b.append(c)

batches = tf.constant(b)


In [40]:
batches

<tf.Tensor: shape=(1, 2, 40), dtype=float32, numpy=
array([[[ 0.9466732 , -0.9517766 ,  0.6089755 , -1.7202418 ,
          0.00536991, -2.1891122 ,  0.22489779, -1.9345222 ,
         -0.64037246,  1.342186  , -0.0755018 ,  1.6919665 ,
         -0.5203122 , -1.8375303 , -2.4220014 , -0.67197025,
          2.5232656 , -2.2110374 ,  3.1824946 , -1.183102  ,
         -1.8224388 , -1.2308848 ,  2.4863615 ,  0.57052153,
         -0.31785262, -1.0713868 , -0.26481   ,  2.1472726 ,
          0.3293893 , -1.3335986 ,  2.2279396 ,  1.374608  ,
         -0.5200319 ,  1.0549773 ,  0.414537  ,  1.4100695 ,
         -0.09097227, -1.5231383 ,  1.1515183 , -0.7249024 ],
        [ 0.9466732 , -0.9517766 ,  0.6089755 , -1.7202418 ,
          0.00536991, -2.1891122 ,  0.22489779, -1.9345222 ,
         -0.64037246,  1.342186  , -0.0755018 ,  1.6919665 ,
         -0.5203122 , -1.8375303 , -2.4220014 , -0.67197025,
          2.5232656 , -2.2110374 ,  3.1824946 , -1.183102  ,
         -1.8224388 , -1.2308848

## Attention Mechanism Testing

In [41]:
importlib.reload(attention)
importlib.reload(masking)

<module 'neuralnetworks.masking' from '/Users/joericks/Desktop/nova/model/neuralnetworks/masking.py'>

In [42]:
attention_mech = attention.PerformerAttention(e_dim, 8)

attention_mech(batches, batches, batches)

<tf.Tensor: shape=(1, 2, 40), dtype=float32, numpy=
array([[[-0.54793596,  1.5718837 , -0.7816968 , -0.04243499,
          0.31416672, -0.97249967, -0.90798515, -0.47719094,
         -0.3950184 , -0.9158306 , -0.78688574, -0.689862  ,
          0.2270847 , -0.7912786 , -0.7128403 ,  0.484177  ,
          0.9981199 ,  0.66749126,  1.8231533 , -1.3570731 ,
         -0.1674463 , -0.17252502, -2.2583406 , -0.23404063,
          0.2119686 , -2.2515857 ,  1.455368  , -0.43291268,
         -0.25599355,  0.12516946, -0.59737355,  1.146447  ,
          1.7000797 ,  0.34244937,  0.95458764,  0.44063324,
          0.42473024,  2.1888547 , -0.25808448,  0.9304709 ],
        [ 0.8838261 ,  0.91367316, -1.4455229 , -1.5507452 ,
         -0.46548843, -0.5916154 ,  0.06613071, -1.7764513 ,
          0.9627501 ,  0.70014507,  0.41408014,  0.61156875,
         -1.1048583 , -0.5744596 , -0.26353523,  0.47219965,
          0.15598807,  1.3493611 , -0.66852957, -0.32535693,
         -2.340591  ,  1.2960248

In [45]:
batches

<tf.Tensor: shape=(1, 2, 40), dtype=float32, numpy=
array([[[ 0.9466732 , -0.9517766 ,  0.6089755 , -1.7202418 ,
          0.00536991, -2.1891122 ,  0.22489779, -1.9345222 ,
         -0.64037246,  1.342186  , -0.0755018 ,  1.6919665 ,
         -0.5203122 , -1.8375303 , -2.4220014 , -0.67197025,
          2.5232656 , -2.2110374 ,  3.1824946 , -1.183102  ,
         -1.8224388 , -1.2308848 ,  2.4863615 ,  0.57052153,
         -0.31785262, -1.0713868 , -0.26481   ,  2.1472726 ,
          0.3293893 , -1.3335986 ,  2.2279396 ,  1.374608  ,
         -0.5200319 ,  1.0549773 ,  0.414537  ,  1.4100695 ,
         -0.09097227, -1.5231383 ,  1.1515183 , -0.7249024 ],
        [ 0.9466732 , -0.9517766 ,  0.6089755 , -1.7202418 ,
          0.00536991, -2.1891122 ,  0.22489779, -1.9345222 ,
         -0.64037246,  1.342186  , -0.0755018 ,  1.6919665 ,
         -0.5203122 , -1.8375303 , -2.4220014 , -0.67197025,
          2.5232656 , -2.2110374 ,  3.1824946 , -1.183102  ,
         -1.8224388 , -1.2308848

## Transformer Testing

In [46]:
importlib.reload(transformer)

<module 'neuralnetworks.transformer' from '/Users/joericks/Desktop/nova/model/neuralnetworks/transformer.py'>

In [48]:
tfrmr = transformer.TransformerLayer(batches.shape[2], batches.shape[0],8 ,20, name = "test_transformer")

In [53]:
tfrmr(batches)

<tf.Tensor: shape=(1, 2, 40), dtype=float32, numpy=
array([[[ 0.21994892, -0.05975333,  0.0789724 , -0.43921822,
         -0.11044189,  0.8868356 ,  0.67162454, -1.096051  ,
          0.4992288 ,  0.5139241 ,  0.14785917, -0.38208514,
         -0.62101895, -0.37262067,  0.04167616,  0.49791864,
         -0.64596516,  0.07079103, -0.2810902 , -0.9351888 ,
         -0.06590635, -0.2972786 , -0.16326918,  0.7278791 ,
         -0.929311  ,  0.8543292 , -0.6946428 , -0.17785752,
         -0.65794134, -0.10700488, -0.23116693, -1.1493764 ,
         -0.38608885,  0.6411152 ,  0.24923731, -0.2929222 ,
         -0.19133559, -0.60280806,  0.02011721,  1.1356254 ],
        [ 0.05286725, -0.8993983 , -0.21018639, -0.26984408,
         -0.33245635, -0.57058895,  0.6576936 , -0.05481829,
          0.17056805,  0.30149615, -0.19358285, -0.35626158,
          0.72556895, -0.18458861,  0.22103399, -0.09815413,
          0.90647614, -0.06192705,  0.08891258, -0.19970153,
         -0.32112715, -0.0117255

In [70]:
embedding_dim = 200

test_string = "hello world"

tkn = tokenizer.Tokenizer()

tkn("hello world")

E_L = embedding.EmbeddingLayer(embedding_dim, name = "embedding")

[E_L(t) for t in tkn.token_q]

E_L.h

{'hello': 0, 'world': 1}

In [57]:
tkn.token_q

['hello', 'world']