# Nova Neural Network Whiteboard

This code is just me experimenting with building my own neural network, none of this has been unit tested, time or memory efficiency optimized, etc...

In [5]:
import numpy as np
from neuralnetworks import fnn, embedding
import importlib

In [95]:
importlib.reload(embedding)

<module 'neuralnetworks.embedding' from '/Users/joericks/Desktop/nova/model/neuralnetworks/embedding.py'>

In [96]:
e_layer = embedding.EmbeddingLayer(100, name = "embedding")

e_layer("hello")
e_layer("world")

<tf.Tensor: shape=(100,), dtype=float32, numpy=
array([ 0.31243145,  1.6632258 ,  1.2573024 , -1.6512637 ,  0.29736254,
        2.1557643 , -0.7013561 ,  0.58076817,  2.169741  ,  2.2590425 ,
        0.34638137,  1.0250777 , -2.4216557 ,  0.78658867,  0.09942935,
       -0.57624614, -0.5109345 , -2.3001287 ,  1.4342275 , -0.17053911,
       -2.3091273 , -2.157223  , -1.035323  ,  0.36069795, -2.520853  ,
        0.48261052, -1.5583143 ,  0.10796907,  1.4343675 , -0.5762365 ,
        0.7285637 ,  2.0106332 ,  2.1278622 ,  0.08499612,  0.5075268 ,
        0.35677117, -1.080905  ,  0.742236  ,  0.11387067, -0.35152408,
        0.64968145, -3.1470046 , -0.8857241 ,  0.5810134 ,  0.32110292,
       -0.83292776,  2.0756316 , -0.51833284,  0.834049  ,  0.26343995,
       -0.17082189, -0.8301311 ,  0.5139759 , -2.2150524 , -0.84129804,
       -2.214689  , -0.67672205, -1.4836304 ,  1.7543744 ,  0.26278627,
        2.1675007 ,  3.206404  ,  3.1903284 ,  3.0959518 , -1.0576005 ,
       -1.548269

In [97]:
other_layer = embedding.EmbeddingLayer(100, name = "other_embedding")

other_layer("!")

other_layer("=")

other_layer (";")

new_layer = e_layer + other_layer

In [99]:
new_layer("")

<tf.Tensor: shape=(100,), dtype=float32, numpy=
array([ 7.38983989e-01,  3.19875932e+00,  3.36644709e-01,  1.29854405e+00,
       -2.49995306e-01,  1.67443514e+00, -4.90961730e-01, -1.65032530e+00,
        6.37550279e-02,  5.66977322e-01,  3.40556651e-01,  7.56609589e-02,
       -1.32443774e+00, -9.23222423e-01,  1.12295115e+00, -1.00889468e+00,
       -2.40938589e-01,  1.37578690e+00,  9.61631477e-01, -1.68321192e+00,
       -1.83286572e+00,  3.12508655e+00, -1.09329730e-01,  1.88812762e-01,
        7.14339793e-01,  1.09181309e+00,  2.22378469e+00, -1.16445804e+00,
        2.02065802e+00,  3.09894204e+00, -1.10969400e+00, -5.72638214e-02,
       -1.19058907e+00, -1.12114477e+00, -9.73630726e-01,  4.77530330e-01,
       -1.94844592e+00, -2.03636813e+00,  6.33223593e-01,  1.78532004e+00,
        5.29739797e-01,  2.32007766e+00, -7.30323672e-01,  7.00678793e-04,
       -2.29549932e+00,  4.83108580e-01, -1.97858214e+00,  5.44873297e-01,
        2.50639224e+00,  2.68776894e+00,  9.08593893

Documentation on softmax and ReLU are provided below: <br>
**[ReLU](https://en.wikipedia.org/wiki/Rectifier_(neural_networks))** <br>
**[softmax](https://en.wikipedia.org/wiki/Softmax_function)**