# Nova Model Whiteboard

This code is just me experimenting with building my own neural network, none of this has been unit tested, time or memory efficiency optimized, etc...

In [1]:
import numpy as np
import tensorflow as tf
from neuralnetworks import fnn, embedding, attention, masking
import importlib

2024-07-27 12:26:37.719928: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
importlib.reload(embedding)

<module 'neuralnetworks.embedding' from '/Users/joericks/Desktop/nova/model/neuralnetworks/embedding.py'>

In [3]:
e_layer = embedding.EmbeddingLayer(100, name = "embedding")

e_layer("hello")
e_layer("world")

<tf.Tensor: shape=(100,), dtype=float32, numpy=
array([ 0.6477791 , -0.35557222,  0.9444278 ,  2.8429859 , -3.024714  ,
       -1.1685808 ,  0.64349514,  0.5852638 ,  0.53181493,  0.15391517,
        1.8202931 ,  0.05456967, -0.5290129 ,  0.31493187, -1.3554447 ,
       -0.80433583,  0.8670971 ,  1.1780598 , -1.3372695 ,  0.541095  ,
        1.1083227 , -0.97951376, -0.43864328, -2.0931735 , -0.61600405,
       -1.0722939 , -0.2806411 , -0.55963665,  0.46039006, -0.10487019,
        1.2743015 ,  1.0603127 ,  1.5245174 , -2.6707604 , -2.0783572 ,
       -0.42965385, -0.06188709,  1.1416861 , -1.7964455 , -1.2561413 ,
       -1.1878856 ,  2.5477479 , -2.2306435 , -1.4924023 ,  0.7328244 ,
        0.13475192, -0.6888018 , -0.7125883 , -0.32054102, -0.7158397 ,
       -0.68810374, -3.1435826 ,  1.981052  , -0.06358787,  0.4221037 ,
        1.455284  , -0.9064363 ,  1.1943806 , -1.2534102 ,  2.205137  ,
        1.3659912 , -1.1681873 ,  0.95943487, -2.2125912 ,  0.07298831,
        2.580864

In [4]:
other_layer = embedding.EmbeddingLayer(100, name = "other_embedding")

other_layer("!")

other_layer("=")

other_layer (";")

new_layer = e_layer + other_layer

In [5]:
new_layer.h

{'hello': 0, 'world': 1, '!': 2, '=': 3, ';': 4}

Documentation on softmax and ReLU are provided below: <br>
**[ReLU](https://en.wikipedia.org/wiki/Rectifier_(neural_networks))** <br>
**[softmax](https://en.wikipedia.org/wiki/Softmax_function)**

In [6]:
#testing the performer attention head

sentence = ['hello', 'world']

idxs = [new_layer.h[s] for s in sentence if s in new_layer.h.keys()]

In [7]:
c = []

for i in idxs:
    c.append(new_layer.embeddings[i].numpy())

In [11]:
# then this process would get iterated based on the batches of training data passed through the model,
# but here we are going to cheat and just make this example be one batch

b = []

b.append(c)

batches = tf.constant(b)


In [16]:
batches.shape[2]

100

In [19]:
importlib.reload(attention)
importlib.reload(masking)

<module 'neuralnetworks.masking' from '/Users/joericks/Desktop/nova/model/neuralnetworks/masking.py'>

In [20]:
attention_mech = attention.PerformerAttention(100, 5, 2)

attention_mech(batches, batches, batches)

tf.Tensor(
[[[-0.33657986 -0.9262262  -0.13162914  0.46635208  0.21719566
   -0.7804447   0.2582785   0.959975   -0.41811702 -0.7652941
   -0.47079676  0.23867448  2.9355624  -1.0908487   0.06961586
   -0.6109851  -0.02972474 -0.89959115 -0.1582937   1.333946
    0.0034052  -1.6867512  -0.7701245   0.02192759  1.2611104
   -0.79242367  0.65403676 -1.0057735  -0.655982   -1.0681647
   -0.7191021   0.58393985  0.00821435  0.09866129 -0.6512082
    0.27102694 -0.13758041  0.9044502  -0.7786741   0.158369
   -0.09599676 -0.3118688   0.7014669   0.9402419   0.17444131
   -0.0633316  -0.5242382   0.9925188  -0.309905   -1.5138011
    1.4615058   1.1631411  -0.6211606   0.81300056 -0.6015385
    0.96887845  1.4441702  -0.37607953  0.7272184  -0.6019401
   -0.69161636  0.21711454  2.206932   -1.5387726   0.6488925
    2.6025724  -1.5902371  -0.43261552  0.47227556 -0.4632857
   -0.03913502 -0.42911303  1.7447426  -0.23306818 -0.44068578
    0.5795478  -3.0680664   0.46491677 -0.21651213  1.975

<tf.Tensor: shape=(1, 4, 100), dtype=float32, numpy=
array([[[ 0.5262648 , -1.4817346 , -0.38872   ,  1.0385944 ,
         -0.93842643,  1.286778  , -0.52472585, -0.41444916,
         -0.8895176 , -0.80216134, -1.2850188 , -0.97965825,
         -0.11113773, -0.14699484,  0.34370854,  1.0258275 ,
         -0.30876175, -0.9852571 , -0.71047866, -0.09097554,
         -2.0081031 , -0.97847885,  2.088754  , -0.07603133,
          0.25725734, -0.36721277,  0.8896126 ,  0.6922748 ,
          1.2284516 ,  0.9713443 ,  0.5788842 ,  0.23102099,
          0.54807603,  1.9943517 , -1.2122364 , -0.2718748 ,
          1.6394578 ,  0.7160789 ,  0.4982461 , -0.5399408 ,
          0.6515386 ,  1.2491443 ,  0.5951017 , -0.9574499 ,
         -0.86294657, -0.64327145,  0.00551314, -0.16733441,
         -1.1969724 ,  0.35619357,  0.42437163, -1.3049009 ,
         -0.44570443, -0.03465661,  0.03079299, -1.9444222 ,
          0.6078634 ,  1.6873872 , -1.1040411 , -0.92290074,
         -0.88604116, -1.3378241