# text datasets

first we are going to build in a real life text datasource from hugging face

In [1]:
from nova_py import parser, tokenizer
from datasets import load_dataset
import itertools
import tensorflow as tf

2025-01-16 23:03:38.235855: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
encoder = parser.Encoder()

In [3]:
tags = encoder.tags

In [4]:
all_combos = []

for j in range(1,4):
    for i in itertools.product(tags.keys(), repeat = j):
        all_combos.append(" -> ".join(i))

In [5]:
encoder.addTransitions(all_combos)

In [6]:
sequences = ["hello world", "sky = \"blue\""]

batch = tokenizer.inBatch(sequences)

batch

<tf.Tensor: shape=(2, 5), dtype=string, numpy=
array([[b'hello', b'world', b'<pad>', b'<pad>', b'<pad>'],
       [b'sky', b'=', b'"', b'blue', b'"']], dtype=object)>

In [7]:
tensor = encoder(batch)

tensor

<tf.Tensor: shape=(2, 5, 2), dtype=string, numpy=
array([[[b'hello', b''],
        [b'world', b''],
        [b'<pad>', b'~pad~'],
        [b'<pad>', b'~pad~'],
        [b'<pad>', b'~pad~']],

       [[b'sky', b''],
        [b'=', b'~relation~'],
        [b'"', b'~container~'],
        [b'blue', b''],
        [b'"', b'~container~']]], dtype=object)>

In [8]:
encoder.TransitionStates

{'': 0,
 '~relation~': 1,
 '~pad~': 2,
 '~var~': 3,
 '~value~': 4,
 '~func~': 5,
 '~break~': 6,
 '~container~': 7,
 '~definition~': 8,
 '~brelation~': 9,
 '~connector~': 10,
 'BAD SEQUENCE ERROR': 11,
 '~relation~ -> ~relation~': 12,
 '~relation~ -> ~pad~': 13,
 '~relation~ -> ~var~': 14,
 '~relation~ -> ~value~': 15,
 '~relation~ -> ~func~': 16,
 '~relation~ -> ~break~': 17,
 '~relation~ -> ~container~': 18,
 '~relation~ -> ~definition~': 19,
 '~relation~ -> ~brelation~': 20,
 '~relation~ -> ~connector~': 21,
 '~relation~ -> BAD SEQUENCE ERROR': 22,
 '~pad~ -> ~relation~': 23,
 '~pad~ -> ~pad~': 24,
 '~pad~ -> ~var~': 25,
 '~pad~ -> ~value~': 26,
 '~pad~ -> ~func~': 27,
 '~pad~ -> ~break~': 28,
 '~pad~ -> ~container~': 29,
 '~pad~ -> ~definition~': 30,
 '~pad~ -> ~brelation~': 31,
 '~pad~ -> ~connector~': 32,
 '~pad~ -> BAD SEQUENCE ERROR': 33,
 '~var~ -> ~relation~': 34,
 '~var~ -> ~pad~': 35,
 '~var~ -> ~var~': 36,
 '~var~ -> ~value~': 37,
 '~var~ -> ~func~': 38,
 '~var~ -> ~break~'

In [14]:
tf.unstack(tensor, axis=2)

[<tf.Tensor: shape=(2, 5), dtype=string, numpy=
 array([[b'hello', b'world', b'<pad>', b'<pad>', b'<pad>'],
        [b'sky', b'=', b'"', b'blue', b'"']], dtype=object)>,
 <tf.Tensor: shape=(2, 5), dtype=string, numpy=
 array([[b'', b'', b'~pad~', b'~pad~', b'~pad~'],
        [b'', b'~relation~', b'~container~', b'', b'~container~']],
       dtype=object)>]