# text datasets

first we are going to build in a real life text datasource from hugging face

In [1]:
from nova_py import parser, tokenizer
# from datasets import load_dataset
import itertools
import tensorflow as tf

2025-01-22 16:56:20.011462: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
encoder = parser.Encoder()

In [3]:
tags = encoder.tags

In [4]:
all_combos = []

for j in range(1,4):
    for i in itertools.product(tags.keys(), repeat = j):
        all_combos.append(" -> ".join(i))

In [5]:
encoder.addTransitions(all_combos)

In [6]:
sequences = ["hello world", "sky = \"blue\""]

batch = tokenizer.inBatch(sequences)

batch

<tf.Tensor: shape=(2, 5), dtype=string, numpy=
array([[b'hello', b'world', b'<pad>', b'<pad>', b'<pad>'],
       [b'sky', b'=', b'"', b'blue', b'"']], dtype=object)>

In [23]:
tensor = encoder(batch)

tensor

<tf.Tensor: shape=(2, 5, 2), dtype=string, numpy=
array([[[b'hello', b'BAD SEQUENCE ERROR'],
        [b'world', b'~value~'],
        [b'<pad>', b'~pad~'],
        [b'<pad>', b'~pad~'],
        [b'<pad>', b'~pad~']],

       [[b'sky', b'~value~'],
        [b'=', b'~relation~'],
        [b'"', b'~container~'],
        [b'blue', b'~var~'],
        [b'"', b'~container~']]], dtype=object)>

2025-01-22 16:48:12.495294: W tensorflow/core/framework/op_kernel.cc:1839] OP_REQUIRES failed at strided_slice_op.cc:117 : INVALID_ARGUMENT: Index out of range using input dim 2; input has only 2 dims
2025-01-22 16:48:12.495324: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: INVALID_ARGUMENT: Index out of range using input dim 2; input has only 2 dims


InvalidArgumentError: {{function_node __wrapped__StridedSlice_device_/job:localhost/replica:0/task:0/device:CPU:0}} Index out of range using input dim 2; input has only 2 dims [Op:StridedSlice] name: strided_slice/

In [14]:
tf.unstack(tensor, axis=2)

[<tf.Tensor: shape=(2, 5), dtype=string, numpy=
 array([[b'hello', b'world', b'<pad>', b'<pad>', b'<pad>'],
        [b'sky', b'=', b'"', b'blue', b'"']], dtype=object)>,
 <tf.Tensor: shape=(2, 5), dtype=string, numpy=
 array([[b'', b'', b'~pad~', b'~pad~', b'~pad~'],
        [b'', b'~relation~', b'~container~', b'', b'~container~']],
       dtype=object)>]