# text datasets

first we are going to build in a real life text datasource from hugging face

In [1]:
from nova_py import parser, tokenizer
# from datasets import load_dataset
import itertools
import tensorflow as tf

2025-01-20 22:41:16.603485: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
encoder = parser.Encoder()

In [3]:
tags = encoder.tags

In [4]:
all_combos = []

for j in range(1,4):
    for i in itertools.product(tags.keys(), repeat = j):
        all_combos.append(" -> ".join(i))

In [5]:
encoder.addTransitions(all_combos)

In [6]:
sequences = ["hello world", "sky = \"blue\""]

batch = tokenizer.inBatch(sequences)

batch

<tf.Tensor: shape=(2, 5), dtype=string, numpy=
array([[b'hello', b'world', b'<pad>', b'<pad>', b'<pad>'],
       [b'sky', b'=', b'"', b'blue', b'"']], dtype=object)>

In [7]:
tensor = encoder(batch)

tensor


~definition~
~pad~



<tf.Tensor: shape=(10,), dtype=string, numpy=
array([b'~definition~', b'~relation~', b'~pad~', b'~pad~', b'~pad~',
       b'~pad~', b'~relation~', b'~container~', b'~var~', b'~container~'],
      dtype=object)>

In [14]:
tf.unstack(tensor, axis=2)

[<tf.Tensor: shape=(2, 5), dtype=string, numpy=
 array([[b'hello', b'world', b'<pad>', b'<pad>', b'<pad>'],
        [b'sky', b'=', b'"', b'blue', b'"']], dtype=object)>,
 <tf.Tensor: shape=(2, 5), dtype=string, numpy=
 array([[b'', b'', b'~pad~', b'~pad~', b'~pad~'],
        [b'', b'~relation~', b'~container~', b'', b'~container~']],
       dtype=object)>]