# text datasets

first we are going to build in a real life text datasource from hugging face

In [1]:
from nova_py.transcribe import MINT
from nova_py import TACO
# from datasets import load_dataset
import itertools
import tensorflow as tf

2025-01-22 18:43:11.290013: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
encoder = MINT()
encoder.cooling_factor

50

In [3]:
tags = encoder.tags

In [4]:
all_combos = []

for j in range(1,4):
    for i in itertools.product(tags.keys(), repeat = j):
        all_combos.append(" -> ".join(i))

In [5]:
encoder.addTransitions(all_combos)

In [6]:
sequences = ["hello world", "sky = \"blue\"", "up is \"down \""]

batch = TACO.inBatch(sequences)

batch

<tf.Tensor: shape=(3, 5), dtype=string, numpy=
array([[b'hello', b'world', b'<pad>', b'<pad>', b'<pad>'],
       [b'sky', b'=', b'"', b'blue', b'"'],
       [b'up', b'is', b'"', b'down', b'"']], dtype=object)>

In [7]:
tensor = encoder(batch)

tensor[:,:,1]

<tf.Tensor: shape=(3, 5), dtype=string, numpy=
array([[b'~container~', b'~definition~', b'~pad~', b'~pad~', b'~pad~'],
       [b'~container~', b'~relation~', b'~container~', b'~definition~',
        b'~container~'],
       [b'~pad~', b'~relation~', b'~container~', b'~pad~',
        b'~container~']], dtype=object)>

In [11]:
encoder.train(tensor, num_epochs = 10)

tf.Tensor(1.0, shape=(), dtype=float64)
tf.Tensor(1.0, shape=(), dtype=float64)
tf.Tensor(1.0, shape=(), dtype=float64)
tf.Tensor(0.9999999999999999, shape=(), dtype=float64)
tf.Tensor(1.0, shape=(), dtype=float64)
tf.Tensor(1.0, shape=(), dtype=float64)
tf.Tensor(0.9999999999999998, shape=(), dtype=float64)
tf.Tensor(1.0, shape=(), dtype=float64)
tf.Tensor(1.0, shape=(), dtype=float64)
tf.Tensor(1.0, shape=(), dtype=float64)
tf.Tensor(0.9999999999999999, shape=(), dtype=float64)
tf.Tensor(1.0, shape=(), dtype=float64)
tf.Tensor(0.9999999999999998, shape=(), dtype=float64)
tf.Tensor(0.9999999999999999, shape=(), dtype=float64)
tf.Tensor(1.0000000000000002, shape=(), dtype=float64)
tf.Tensor(0.9999999999999999, shape=(), dtype=float64)
tf.Tensor(0.9999999999999998, shape=(), dtype=float64)
tf.Tensor(1.0, shape=(), dtype=float64)
tf.Tensor(1.0, shape=(), dtype=float64)
tf.Tensor(1.0, shape=(), dtype=float64)
tf.Tensor(0.9999999999999998, shape=(), dtype=float64)
tf.Tensor(1.0, shape=(), 

In [12]:
encoder.TransitionMatrix[0,:]

<tf.Tensor: shape=(11,), dtype=float64, numpy=
array([0.04729352, 0.23777014, 0.04729352, 0.04729352, 0.04729352,
       0.04729352, 0.33658817, 0.04729352, 0.04729352, 0.04729352,
       0.04729352])>

In [9]:
train_tensor

[]

In [10]:
tensor

<tf.Tensor: shape=(3, 5, 2), dtype=string, numpy=
array([[[b'hello', b'~definition~'],
        [b'world', b'~container~'],
        [b'<pad>', b'~pad~'],
        [b'<pad>', b'~pad~'],
        [b'<pad>', b'~pad~']],

       [[b'sky', b'~pad~'],
        [b'=', b'~relation~'],
        [b'"', b'~container~'],
        [b'blue', b'~relation~'],
        [b'"', b'~container~']],

       [[b'up', b'~container~'],
        [b'is', b'~relation~'],
        [b'"', b'~container~'],
        [b'down', b'~connector~'],
        [b'"', b'~container~']]], dtype=object)>