In [1]:
from nova_py import nova, TACO
import tensorflow as tf
import numpy as np
import ast

2025-03-09 16:44:26.148198: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
model = nova.Model()

test_case = ["hello =\"world!\""]

In [4]:
response = model.generate(test_case, pretty_print=True)

NotEqasnameContinuetargetifsUSubis_asyncoptional_varsDictCompBinOpTrueSliceNameupperbasesBoolOpFormattedValueEqContinueCompareForStarredIfExpIfExpAwaitYieldFromeltsmoduleDeleteStoregeneratorsReturnWithrightlowerLtEasnamekeywordSetCompekwonlyargsClassDefoperand+kindBoolOpForSetCompAwaitopsFunctionDef]easnameClassDefifsWithbAttributeBreakSetComprightCalleltNonectxAttributeBreakkeywordsargumentsis_asyncContinue,returnsIfargumentsattrsliceFloorDivIfExpkindReturnoperandAddgeneratorshandlersTupleConstantIfExpexcwithitemReturnExceptHandlerWithImportFrom]WhilevarargImportLttype_ignoresBreakgeneratorsLShiftkw_defaults+posonlyargscomprehensionOrkeywordsoperandSub]keywordGtEaliasAsyncFunctionDefFormattedValuerightis_asyncLtEIncomprehensioncausedefaultsAssertConstant#VARIABLEAwait=NameUSubGtESub)InaliasIfExpopasnameContinueFormattedValueFormattedValueUSubFalseTrueDelStorereturnsLt-namesStore[funcoptional_vars)attropdecorator_listIsSubscripteltIfExpkw_defaultsposonlyargsposonlyargsBreakfinalbodyDel

In [5]:
ground_truths = list([ast.dump(tree, indent = 3) for tree in map(ast.parse, test_case)])
ground_truths

["Module(\n   body=[\n      Assign(\n         targets=[\n            Name(id='hello', ctx=Store())],\n         value=Constant(value='world!'))],\n   type_ignores=[])"]

In [6]:
TACO.inBatch(test_case)

<tf.Tensor: shape=(1, 5), dtype=string, numpy=array([[b'hello', b'=', b'"', b'world!', b'"']], dtype=object)>

In [7]:
test1 = model.train(test_case, ground_truths)

(1, 160)
(2, 160)
(3, 160)
(4, 160)
(5, 160)
(6, 160)
(7, 160)
(8, 160)
(9, 160)
(10, 160)
(11, 160)
(12, 160)
(13, 160)
(14, 160)
(15, 160)
(16, 160)
(17, 160)
(18, 160)
(19, 160)
(20, 160)
(21, 160)
(22, 160)
(23, 160)
(24, 160)
(25, 160)
(26, 160)
(27, 160)
(28, 160)
(29, 160)
(30, 160)
(31, 160)
(32, 160)
(33, 160)
(34, 160)
(35, 160)
(36, 160)
(37, 160)
(38, 160)
(39, 160)
(40, 160)
(41, 160)
(42, 160)
(43, 160)
(44, 160)


In [8]:
test1

<tf.Tensor: shape=(45, 160), dtype=float32, numpy=
array([[0.00208615, 0.00499338, 0.00407013, ..., 0.00556333, 0.00147481,
        0.0015916 ],
       [0.00503054, 0.00443653, 0.00153479, ..., 0.01366237, 0.00706134,
        0.00715778],
       [0.00496345, 0.00315347, 0.00600285, ..., 0.00395365, 0.0022843 ,
        0.00799787],
       ...,
       [0.02976536, 0.00213027, 0.01984709, ..., 0.00659936, 0.00613126,
        0.0102134 ],
       [0.02001444, 0.00300171, 0.01301008, ..., 0.00583098, 0.00643752,
        0.00501724],
       [0.00280647, 0.00252861, 0.00294635, ..., 0.00352967, 0.00045182,
        0.00156282]], dtype=float32)>