In [1]:
from nova_py import TACO
import tensorflow as tf
from nova_py.architecture import embedding

2025-03-23 22:06:43.299813: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
code_str = ''' 
class AST:
    def __init__(self):
        pass

def hello_world(test):
    return test
'''

other_str = '''test'''

In [3]:
TACO.batch([code_str, other_str])

(<tf.Tensor: shape=(2, 37), dtype=int32, numpy=
 array([[ 1321,  1128,    28,  3754,    55,    77,  1414,    15,  8988,
          1923,  1929,  8988,    69,  2914,  2215,    70,    77,  2610,
          2928,  1414,    15,  1814,  2221,  2588,  3324,  2821,    13,
            69,  3014,  2929,    70,    77,  2814,  3030,  2823,  3014,
          2929],
        [ 3014,  2929, 10100, 10100, 10100, 10100, 10100, 10100, 10100,
         10100, 10100, 10100, 10100, 10100, 10100, 10100, 10100, 10100,
         10100, 10100, 10100, 10100, 10100, 10100, 10100, 10100, 10100,
         10100, 10100, 10100, 10100, 10100, 10100, 10100, 10100, 10100,
         10100]], dtype=int32)>,
 <tf.Tensor: shape=(2, 18), dtype=int32, numpy=
 array([[3, 2, 1, 2, 4, 1, 2, 1, 1, 2, 2, 6, 1, 2, 1, 1, 3, 2],
        [2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
       dtype=int32)>)

In [5]:
embedding_test = embedding.Layer(d_model = 10, N=10100)

In [6]:
embedding_test.embeddings

<tf.Variable 'Variable:0' shape=(10100, 10) dtype=float32, numpy=
array([[-0.01329554,  0.01934609,  0.01987418, ..., -0.02162934,
        -0.00544346,  0.01824301],
       [-0.01016369, -0.02077285,  0.02225867, ...,  0.01458584,
        -0.00446836, -0.02089825],
       [ 0.012869  , -0.009697  ,  0.01644907, ...,  0.02172651,
        -0.00642405, -0.00900532],
       ...,
       [-0.02365198,  0.00185447,  0.0003818 , ...,  0.00019872,
        -0.00571606, -0.01539276],
       [-0.00020033, -0.0154217 , -0.00326702, ...,  0.02274549,
         0.01585326,  0.0241295 ],
       [ 0.01602439,  0.00445597, -0.00530677, ...,  0.01446839,
         0.00079913,  0.01721573]], dtype=float32)>

In [10]:
embedding_test(2)

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([ 0.012869  , -0.009697  ,  0.01644907, -0.01600126,  0.01733674,
        0.0135118 ,  0.01830292,  0.02172651, -0.00642405, -0.00900532],
      dtype=float32)>